language: csharp
solution: backend/backend.sln
dotnet: 1.0.0-preview2-003121
dist: trusty
sudo: required
notifications:
  email: false
script:
  - cd backend && dotnet restore && dotnet build
  - cd ../frontend && npm install && gulp